// @incy/link-encoder
//
// Encode subscription URLs into `incy://crypt1/<payload>` deep links
// that the INCY iOS/Android/Desktop clients know how to decode.
//
// ⚠️  THIS IS OBFUSCATION, NOT SECURITY.
//
// The AES-256-GCM key K1 is derived from constants and binary asset
// bytes embedded in this package — anyone reading the source can
// reconstruct it. The same K1 already lives inside every shipped INCY
// client app (iOS IPA, Android APK, Desktop installer), where it is
// also extractable by a reverse engineer. Publishing this package
// reveals nothing new; it just acknowledges the offline-decryption
// limitation honestly.
//
// What we DO defend against:
//   ✅  Telegram chat moderation bots scanning for VPN-URL patterns
//   ✅  Russian regulator (RKN) automated scanners
//   ✅  Casual users accidentally pasting plaintext URLs in screenshots
//   ✅  `grep` over chat dumps / supply-chain string scanners
//
// What we DON'T defend against:
//   ❌  A determined reverse engineer with Frida — the key materialises
//       in memory at the moment `AES.GCM.seal()` runs, regardless of
//       how it was derived. Same applies on the client side.
//
// If the key is ever burnt publicly, the INCY clients ship a new
// release adding `crypt2/` (different salt parts + different keymat
// asset bytes). Existing `crypt1/` links in chat histories keep
// working forever — clients never remove the old scheme from their
// decoder table.

import { createCipheriv, createDecipheriv, createHash, randomBytes } from 'node:crypto';
import { KEYMAT_A_B64, KEYMAT_B_B64 } from './keymat.js';

// --- Salt parts. These four strings are concatenated in order and
// fed into the SHA-256 KDF. They live as separate constants so that
// — like in the client apps — a single-file grep doesn't reveal the
// full salt at once. Yes, you can see all four right here. Read the
// header comment again.

const SALT_P1 = 'incy';
const SALT_P2 = 'deep';
const SALT_P3 = 'crypt1';
const SALT_P4 = 'v2026.06';

// --- Keymat layout. Two opaque 4 KiB blobs are inlined as base64 in
// `keymat.ts` (auto-generated from `assets/incy_assets_a.bin` and
// `assets/incy_assets_b.bin`). The KDF pulls 32 bytes from each at
// fixed offsets. Identical bytes ship inside the iOS/Android/Desktop
// apps so a link generated by this package decodes on every platform
// bit-for-bit.
//
// Why inline instead of `fs.readFileSync('assets/…')`: bundlers
// (Vite, webpack, Next.js, Cloudflare Workers, etc.) handle constants
// natively; filesystem reads break in serverless / edge / browser
// targets. Inlining keeps the package isomorphic.

const KEYMAT_A_OFFSET = 1024;
const KEYMAT_B_OFFSET = 2048;
const KEYMAT_LEN = 32;

const EXPECTED_KEY_FINGERPRINT =
  'b6bf708471cc90043232967660aade86a50b4e57929db2e53c5fa34db624c08c';

const SCHEME = 'incy';
const HOST = 'crypt1';

let keyCache: Buffer | undefined;

function deriveKey(): Buffer {
  if (keyCache) return keyCache;
  const a = Buffer.from(KEYMAT_A_B64, 'base64');
  const b = Buffer.from(KEYMAT_B_B64, 'base64');
  if (a.length < KEYMAT_A_OFFSET + KEYMAT_LEN || b.length < KEYMAT_B_OFFSET + KEYMAT_LEN) {
    throw new Error('incy-link-encoder: keymat assets are smaller than expected');
  }
  const kmA = a.subarray(KEYMAT_A_OFFSET, KEYMAT_A_OFFSET + KEYMAT_LEN);
  const kmB = b.subarray(KEYMAT_B_OFFSET, KEYMAT_B_OFFSET + KEYMAT_LEN);
  const seed = Buffer.concat([
    Buffer.from(SALT_P1, 'utf8'),
    Buffer.from(SALT_P2, 'utf8'),
    Buffer.from(SALT_P3, 'utf8'),
    Buffer.from(SALT_P4, 'utf8'),
    kmA,
    kmB,
  ]);
  const k = createHash('sha256').update(seed).digest();
  const fp = createHash('sha256').update(k).digest('hex');
  if (fp !== EXPECTED_KEY_FINGERPRINT) {
    throw new Error(
      `incy-link-encoder: derived K1 fingerprint mismatch (expected ${EXPECTED_KEY_FINGERPRINT}, got ${fp}) — ` +
        `keymat assets are out of sync with the published clients. Reinstall the package or report a bug.`
    );
  }
  keyCache = k;
  return k;
}

// --- Base64url helpers (no padding, matches RFC 4648 §5).

function b64urlEncode(buf: Buffer): string {
  return buf
    .toString('base64')
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/g, '');
}

function b64urlDecode(s: string): Buffer {
  const padded = s.replace(/-/g, '+').replace(/_/g, '/');
  const pad = padded.length % 4 === 0 ? '' : '='.repeat(4 - (padded.length % 4));
  return Buffer.from(padded + pad, 'base64');
}

// --- Compact JSON with stable key order. iOS uses
// `JSONSerialization` with `.sortedKeys`; Android/Desktop hand-roll
// the same. We do the same here so the GCM-authenticated bytes are
// byte-for-byte identical on every platform.

function sortedCompactJson(payload: Record<string, unknown>): string {
  const keys = Object.keys(payload).sort();
  const parts = keys.map((k) => `${JSON.stringify(k)}:${JSON.stringify(payload[k])}`);
  return `{${parts.join(',')}}`;
}

// --- Public API ----------------------------------------------------

/** Optional metadata attached to an encrypted link. */
export interface EncryptOptions {
  /**
   * Human-readable subscription name. The receiving app shows this
   * in the import confirmation sheet (e.g. "MyProvider VPN — Confirm
   * import?"). Truncated to 128 chars by clients.
   */
  name?: string;
}

/**
 * Encrypt a subscription URL into an `incy://crypt1/<payload>` deep
 * link string. The URL must be an http(s) subscription endpoint —
 * v2ray/vless/trojan share links are not yet supported in v1.
 *
 * Throws if the URL is empty.
 */
export function encryptLink(url: string, opts: EncryptOptions = {}): string {
  if (!url || typeof url !== 'string') {
    throw new TypeError('encryptLink: url must be a non-empty string');
  }
  const key = deriveKey();
  const payload: Record<string, unknown> = { url, v: 1 };
  if (opts.name && opts.name.length > 0) {
    payload.n = opts.name.slice(0, 128);
  }
  const plaintext = Buffer.from(sortedCompactJson(payload), 'utf8');

  const iv = randomBytes(12);
  const cipher = createCipheriv('aes-256-gcm', key, iv);
  const ct = Buffer.concat([cipher.update(plaintext), cipher.final()]);
  const tag = cipher.getAuthTag();

  const wire = Buffer.concat([iv, ct, tag]);
  return `${SCHEME}://${HOST}/${b64urlEncode(wire)}`;
}

/** Optional explicit IV — for deterministic tests. */
export interface EncryptDeterministicOptions extends EncryptOptions {
  iv: Buffer;
}

/**
 * Same as `encryptLink` but takes a caller-provided IV. Useful for
 * test vectors / reproducibility. **Do not** reuse an IV across
 * different plaintexts in production — that breaks AES-GCM
 * confidentiality.
 */
export function encryptLinkDeterministic(
  url: string,
  opts: EncryptDeterministicOptions
): string {
  if (opts.iv.length !== 12) {
    throw new TypeError('encryptLinkDeterministic: iv must be 12 bytes');
  }
  const key = deriveKey();
  const payload: Record<string, unknown> = { url, v: 1 };
  if (opts.name && opts.name.length > 0) {
    payload.n = opts.name.slice(0, 128);
  }
  const plaintext = Buffer.from(sortedCompactJson(payload), 'utf8');

  const cipher = createCipheriv('aes-256-gcm', key, opts.iv);
  const ct = Buffer.concat([cipher.update(plaintext), cipher.final()]);
  const tag = cipher.getAuthTag();

  const wire = Buffer.concat([opts.iv, ct, tag]);
  return `${SCHEME}://${HOST}/${b64urlEncode(wire)}`;
}

/** Result of decrypting a `incy://crypt1/...` link. */
export interface DecryptedLink {
  /** The embedded subscription URL. */
  url: string;
  /** Optional human-readable name supplied at encrypt time. */
  name?: string;
}

/**
 * Decrypt a `incy://crypt1/<payload>` deep link back to its
 * subscription URL + optional name. Throws on malformed input or
 * authentication failure (wrong key, tampered ciphertext).
 *
 * Used mainly for verification / testing — production decryption
 * happens inside the INCY client apps.
 */
export function decryptLink(link: string): DecryptedLink {
  if (!link || typeof link !== 'string') {
    throw new TypeError('decryptLink: link must be a non-empty string');
  }
  const prefix = `${SCHEME}://${HOST}/`;
  if (!link.startsWith(prefix)) {
    throw new Error(`decryptLink: expected ${prefix} prefix`);
  }
  const payload = link.slice(prefix.length).replace(/\/+$/g, '');
  if (payload.length === 0) {
    throw new Error('decryptLink: empty payload');
  }
  const wire = b64urlDecode(payload);
  if (wire.length < 12 + 16 + 1) {
    throw new Error('decryptLink: payload too short');
  }
  const iv = wire.subarray(0, 12);
  const tag = wire.subarray(wire.length - 16);
  const ct = wire.subarray(12, wire.length - 16);

  const key = deriveKey();
  const decipher = createDecipheriv('aes-256-gcm', key, iv);
  decipher.setAuthTag(tag);
  let plaintext: Buffer;
  try {
    plaintext = Buffer.concat([decipher.update(ct), decipher.final()]);
  } catch {
    throw new Error('decryptLink: authentication failed');
  }

  let parsed: { url?: unknown; n?: unknown; v?: unknown };
  try {
    parsed = JSON.parse(plaintext.toString('utf8'));
  } catch {
    throw new Error('decryptLink: malformed plaintext');
  }
  if (typeof parsed.url !== 'string' || parsed.url.length === 0) {
    throw new Error('decryptLink: missing url field');
  }
  const result: DecryptedLink = { url: parsed.url };
  if (typeof parsed.n === 'string' && parsed.n.length > 0) result.name = parsed.n;
  return result;
}

/**
 * Library version + key fingerprint. Useful when reporting bugs or
 * verifying the client/server are running compatible builds.
 */
export const VERSION = '1.0.0';
export const SCHEME_VERSION = 'crypt1';
export const KEY_FINGERPRINT = EXPECTED_KEY_FINGERPRINT;
